# Generated by Django 5.0.7 on 2024-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterland',
            old_name='rides',
            new_name='rides_name',
        ),
        migrations.AddField(
            model_name='waterland',
            name='category',
            field=models.CharField(choices=[('child', 'child'), ('adult', 'adult')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
